import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./styles/page.css";
import Header from "./layout/Header";
import Sidebar from "./layout/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}
      >
        <main className="wood flex flex-col">
          <Header></Header>
            <div className="flex h-[calc(100dvh-24px-var(--text-2xl)*var(--text-2xl--line-height))]">
              <Sidebar></Sidebar>
              {children}
            </div>
        </main>
      </body>
    </html>
  );
}
